# Generated by Django 4.1.4 on 2022-12-16 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('address', models.CharField(max_length=30, verbose_name='address')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('budget', models.IntegerField(verbose_name='budget')),
                ('arena', models.ManyToManyField(help_text='choose arenas for this team', to='basketball.arena', verbose_name='Arena(s)')),
                ('sponsors', models.ManyToManyField(help_text='choose sponsors for the team', to='basketball.sponsor', verbose_name='sponsor(s)')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('surname', models.CharField(max_length=30, verbose_name='surname')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('salary', models.IntegerField(verbose_name='salary')),
                ('responsibility', models.CharField(max_length=20, verbose_name='responsibility')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='photo')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketball.team', verbose_name='team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.IntegerField(verbose_name='jersey_number')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('surname', models.CharField(max_length=30, verbose_name='surname')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('height', models.IntegerField(verbose_name='height')),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('position', models.CharField(choices=[('C', 'Center'), ('PF', 'Power Forward'), ('SF', 'Small Forward'), ('SG', 'Shooting Guard'), ('PG', 'Point Guard')], max_length=2, verbose_name='position')),
                ('salary', models.IntegerField(verbose_name='salary')),
                ('birth_country', models.CharField(max_length=20, verbose_name='birth_country')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='photo')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketball.team', verbose_name='team')),
            ],
        ),
    ]
