# Generated by Django 4.1.4 on 2022-12-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['name'], 'verbose_name': 'sponsor', 'verbose_name_plural': 'sponsors'},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='sponsors',
            new_name='sponsor',
        ),
        migrations.AlterField(
            model_name='arena',
            name='address',
            field=models.CharField(max_length=50, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='arena',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
