# Generated by Django 4.1.4 on 2022-12-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0002_alter_sponsor_options_rename_sponsors_team_sponsor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='arena',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='arena',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arenas', to='basketball.team', verbose_name='team'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='basketball.team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='basketball.team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='basketball.team', verbose_name='team'),
        ),
    ]
