# Generated by Django 4.1.4 on 2022-12-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0004_alter_player_photo_alter_player_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='responsibility',
            field=models.CharField(max_length=50, verbose_name='responsibility'),
        ),
    ]
