# Generated by Django 4.1.3 on 2022-12-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0005_alter_player_photo_alter_staff_responsibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='history',
            field=models.TextField(default='', max_length=3000, verbose_name='history'),
        ),
    ]
